# Generated by Django 3.1.7 on 2021-05-04 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_puzzlesolve_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzlesolve',
            name='duration',
        ),
        migrations.AddField(
            model_name='puzzlesolve',
            name='unlock_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time between the puzzle unlocked and its solve'),
        ),
    ]
