# Generated by Django 3.1.7 on 2021-05-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20210504_1721'),
        ('teams', '0003_auto_20210504_2208'),
    ]

    operations = [
    ]
