# Generated by Django 3.1.7 on 2021-05-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_episode_unlocks'),
        ('teams', '0005_merge_20210504_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpageproxyobject',
            options={'verbose_name': 'info page', 'verbose_name_plural': '      Info pages'},
        ),
        migrations.AlterModelOptions(
            name='guess',
            options={'verbose_name_plural': '     Guesses'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': '        Persons'},
        ),
        migrations.AlterModelOptions(
            name='puzzlesolve',
            options={'verbose_name_plural': '    Puzzles solved by teams'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': '         Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamepisodelink',
            options={'verbose_name_plural': ' Episodes unlocked by teams'},
        ),
        migrations.AlterModelOptions(
            name='teameurekalink',
            options={'verbose_name_plural': 'Eurekas unlocked by teams'},
        ),
        migrations.AlterModelOptions(
            name='teampuzzlelink',
            options={'verbose_name_plural': '   Puzzles unlocked by teams'},
        ),
        migrations.AlterModelOptions(
            name='userproxyobject',
            options={'ordering': ['-pk'], 'verbose_name': 'user', 'verbose_name_plural': '       Users'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='solved',
            new_name='puz_solved',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='unlocked',
            new_name='puz_unlocked',
        ),
        migrations.RemoveField(
            model_name='teamepisodelink',
            name='time',
        ),
        migrations.AlterField(
            model_name='team',
            name='ep_unlocked',
            field=models.ManyToManyField(blank=True, help_text='The episodes the team has unlocked', related_name='ep_unlocked_for', through='teams.TeamEpisodeLink', to='hunts.Episode'),
        ),
        migrations.CreateModel(
            name='EpisodeSolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text='The time the episode was finished by this team')),
                ('episode', models.ForeignKey(help_text='The puzzle that this is a solve for', on_delete=django.db.models.deletion.CASCADE, to='hunts.episode')),
                ('team', models.ForeignKey(help_text='The team that this solve is from', on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'verbose_name_plural': '  Episode solved by teams',
                'unique_together': {('episode', 'team')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='ep_solved',
            field=models.ManyToManyField(blank=True, help_text='The episodes the team has solved', related_name='ep_solved_for', through='teams.EpisodeSolve', to='hunts.Episode'),
        ),
    ]
