# Generated by Django 3.1.7 on 2021-05-07 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210506_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secret token displayed to the team members to join their discord role'),
        ),
    ]
