# Generated by Django 3.1.7 on 2021-05-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20210511_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord_linked',
            field=models.BooleanField(default=False, help_text='True if the team has joined a discord channel (is then forbidden to change name for consistency)'),
        ),
    ]
