version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/volumes/db_data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - ./docker/volumes/redis_data:/data

  app:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
    image: django_puzzlehunt  # Name image for use in huey
    restart: always
    volumes:
      - .:/code  # Enables live modification of django files
      - static:/static
      - media:/media
      - ./docker/volumes/logs:/var/log/external
      - uploads_puzzles:/uploads/puzzles
      - uploads_solutions:/uploads/solutions
    environment:
      - DOMAIN
      - DJANGO_SECRET_KEY
      - DJANGO_ENABLE_DEBUG
      - DJANGO_EMAIL_USER
      - DJANGO_EMAIL_PASSWORD
      - DJANGO_USE_SHIBBOLETH
      - DJANGO_SETTINGS_MODULE=server.settings
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      - ENABLE_DEBUG_TOOLBAR
      - SENTRY_DSN
    depends_on:
      - db
      - redis

  huey:
    image: django_puzzlehunt # re-use above image
    command: bash -c "python /code/manage.py migrate --no-input && python /code/manage.py run_huey --quiet"
    restart: always
    volumes:
      - .:/code
      - static:/static
      - media:/media
      - ./docker/volumes/logs:/var/log/external
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_SETTINGS_MODULE=server.settings
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      - SENTRY_DSN
    depends_on:
      - app

  web:
    image: nginx
    restart: always
    depends_on:
      - app
    ports:
        - "8080:80"
        - "443:443"
    volumes:
      - static:/static
      - media:/media
      - ./docker/volumes/ssl-certs/:/etc/nginx/ssl/
      - ./docker/configs/nginx_${NGINX_PROTOCOL}.conf:/etc/nginx/conf.d/default.conf
    environment:
      - DOMAIN
      - CONTACT_EMAIL
    tty: true

volumes:
  static:
  media:
  uploads_puzzles: {}
  uploads_solutions: {}
