# Generated by Django 3.1.7 on 2021-05-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='unlocks',
            field=models.ForeignKey(help_text='Episode that this episode is a possible prerequisite for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunts.episode'),
        ),
    ]
