# Generated by Django 3.1.7 on 2021-05-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_episode_unlocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='unlocks',
            field=models.ForeignKey(blank=True, help_text='Episode that this episode is a possible prerequisite for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunts.episode'),
        ),
    ]
