# Generated by Django 3.1.7 on 2021-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_auto_20210507_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='If yes, then all puzzles are available to everybody as prepuzzles (and hints / eurekas do not work)'),
        ),
    ]
