# Generated by Django 3.1.7 on 2021-05-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0005_hunt_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='template',
            field=models.TextField(default='', help_text='The template string to be rendered to HTML on the puzzle page'),
        ),
    ]
