# Generated by Django 3.1.7 on 2021-05-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0006_hunt_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prepuzzle',
        ),
    ]
