# Generated by Django 3.1.7 on 2021-05-11 08:53

import django.contrib.postgres.fields
from django.db import migrations, models
import hunts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0008_episode_headstarts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='headstarts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), default=hunts.models.Episode.get_headstarts_default, help_text='Headstart gained by the first, second, etc, finishing teams for the next episode', size=None),
        ),
    ]
