# Generated by Django 3.1.7 on 2021-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0009_auto_20210511_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='template',
            field=models.TextField(default='', help_text='The template string to be rendered to HTML on the puzzle page', null=True),
        ),
    ]
