# Generated by Django 3.1.7 on 2021-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0010_auto_20210511_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='end_date',
            field=models.DateTimeField(help_text='The date/time at which a hunt will be archived and available to the public / stats will be released'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='start_date',
            field=models.DateTimeField(help_text='The date/time at which the hunt page will become visible to registered users'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='template',
            field=models.TextField(blank=True, default='', help_text='The template string to be rendered to HTML on the puzzle page', null=True),
        ),
    ]
