# Generated by Django 3.1.7 on 2021-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0012_auto_20210512_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='demo_response',
            field=models.TextField(blank=True, default='', help_text='For demo puzzles, this string will be displayed when the solution is found'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='answer_regex',
            field=models.CharField(blank=True, default='', help_text='The regexp towards which the guess is checked in addition to the answer (optional, not used for demo puzzles)', max_length=100),
        ),
    ]
